### ISSUE TITLE
Unexpected value 'DialogModule' imported by the module 'AppModule'

### ISSUE THREAD

**Issue by adrienverge** [ammar91/aot-primeng#1]
Hi @ammar91,

As first reported in [primeng#1004](https://github.com/primefaces/primeng/pull/1004#issuecomment-251885435), running `ngc` fails on my system.

Steps followed:

```
git clone https://github.com/ammar91/aot-primeng.git
cd aot-primeng
npm i
rm -rf node_modules/primeng
cp -r primeng-aot-build node_modules/primeng
npm run ngc
```

Error output by `npm run ngc`:

```
> Invoicing@1.0.0 ngc /tmp/aot-primeng
> ngc -p ./tsconfig.aot.json

Error: Unexpected value 'DialogModule' imported by the module 'AppModule'
    at /tmp/aot-primeng/node_modules/@angular/compiler/bundles/compiler.umd.js:14109:37
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (/tmp/aot-primeng/node_modules/@angular/compiler/bundles/compiler.umd.js:14094:46)
    at /tmp/aot-primeng/node_modules/@angular/compiler/bundles/compiler.umd.js:12936:58
    at Array.forEach (native)
    at OfflineCompiler.analyzeModules (/tmp/aot-primeng/node_modules/@angular/compiler/bundles/compiler.umd.js:12935:21)
    at CodeGenerator.codegen (/tmp/aot-primeng/node_modules/@angular/compiler-cli/src/codegen.js:105:47)
    at codegen (/tmp/aot-primeng/node_modules/@angular/compiler-cli/src/main.js:7:81)
    at Object.main (/tmp/aot-primeng/node_modules/@angular/compiler-cli/node_modules/@angular/tsc-wrapped/src/main.js:30:16)
    at Object.<anonymous> (/tmp/aot-primeng/node_modules/@angular/compiler-cli/src/main.js:14:9)
Compilation failed
```

Version information:

```
$ grep version node_modules/@angular/core/package.json
  "version": "2.0.1",
$ grep version node_modules/@angular/compiler/package.json
  "version": "2.0.1",
$ grep version node_modules/@angular/compiler-cli/package.json
  "version": "0.6.3",
$ tsc --version
Version 2.0.3
```

**Comment by ammar91** [comment]
@adrienverge Sorry, `primeng.js` were missing, can you please take the latest and try again. It should work. 

Also, 

> cp -r primeng-aot-build node_modules/primeng
> should be
> cp -r primeng-aot-build/primeng node_modules/primeng

**Comment by adrienverge** [comment]
Now it's working! Thanks!
